export const animals = [
  {"id": 142,"file-name": "duk16","name": {"name-en": "Molly","name-eneu": "Molly","name-de": "Monika","name-sp": "Deira","name-spus": "Deira","name-fr": "Molly","name-frus": "Molly","name-it": "Molly","name-nl": "Molly","name-cn": "亚美","name-tw": "亞美","name-jp": "カモミ","name-kr": "귀오미","name-ru": "Молли"},"personality": "Normal","birthday-string": "March 7th","birthday": "7/3","species": "Duck","gender": "Female","catch-phrase": "quackidee"},
  {"id": 228,"file-name": "kal10","name": {"name-en": "Eugene","name-eneu": "Eugene","name-de": "Sunny","name-sp": "Eucalín","name-spus": "Eucalín","name-fr": "Jamy","name-frus": "Jamy","name-it": "Corrado","name-nl": "Eugene","name-cn": "罗奇","name-tw": "羅奇","name-jp": "ロッキー","name-kr": "코알","name-ru": "Юджин"},"personality": "Smug","birthday-string": "October 26th","birthday": "26/10","species": "Koala","gender": "Male","catch-phrase": "yeahbuddy"},
  {"id": 150,"file-name": "elp06","name": {"name-en": "Axel","name-eneu": "Axel","name-de": "Axel","name-sp": "Eustakio","name-spus": "Eustakio","name-fr": "Axel","name-frus": "Axel","name-it": "Sandro","name-nl": "Axel","name-cn": "大大","name-tw": "大大","name-jp": "エックスエル","name-kr": "엑스엘리","name-ru": "Аксель"},"personality": "Jock","birthday-string": "March 23rd","birthday": "23/3","species": "Elephant","gender": "Male","catch-phrase": "WHONK"},
  {"id": 335,"file-name": "rbt18","name": {"name-en": "Cole","name-eneu": "Cole","name-de": "Karl","name-sp": "Nicolás","name-spus": "Nicolás","name-fr": "Épicure","name-frus": "Épicure","name-it": "Lello","name-nl": "Cole","name-cn": "阿甘","name-tw": "阿甘","name-jp": "アマミン","name-kr": "아마민","name-ru": "Коул"},"personality": "Lazy","birthday-string": "August 10th","birthday": "10/8","species": "Rabbit","gender": "Male","catch-phrase": "coooooool"},
  {"id": 26,"file-name": "brd03","name": {"name-en": "Twiggy","name-eneu": "Twiggy","name-de": "Twiggy","name-sp": "Tití","name-spus": "Tití","name-fr": "Titi","name-frus": "Titi","name-it": "Titti","name-nl": "Twiggy","name-cn": "叽叽","name-tw": "嘰嘰","name-jp": "ピーチク","name-kr": "핀틱","name-ru": "Твигги"},"personality": "Peppy","birthday-string": "July 13th","birthday": "13/7","species": "Bird","gender": "Female","catch-phrase": "cheepers"},
  {"id": 22,"file-name": "bea15","name": {"name-en": "Megan","name-eneu": "Megan","name-de": "Dagmar","name-sp": "Carmela","name-spus": "Carmela","name-fr": "Candy","name-frus": "Candy","name-it": "Dolcinia","name-nl": "Megan","name-cn": "糖果","name-tw": "糖果","name-jp": "キャンディ","name-kr": "캔디","name-ru": "Меган"},"personality": "Normal","birthday-string": "March 13th","birthday": "13/3","species": "Bear","gender": "Female","catch-phrase": "sundae"},
  {"id": 188,"file-name": "gor09","name": {"name-en": "Rocket","name-eneu": "Rocket","name-de": "Katrin","name-sp": "Gloria","name-spus": "Gloria","name-fr": "Gertrude","name-frus": "Gertrude","name-it": "Kinga","name-nl": "Rocket","name-cn": "阿四","name-tw": "阿四","name-jp": "４ごう","name-kr": "4호","name-ru": "Рокет"},"personality": "Uchi","birthday-string": "April 14th","birthday": "14/4","species": "Gorilla","gender": "Female","catch-phrase": "vroom"},

];
